title: Just a first test
author: cmonlind

description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet consectetur adipiscing elit vestibulum.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
